### ISSUE TITLE
Rename .private folder

### ISSUE THREAD

**Issue by bojjenclon** [mouse0270/fantasy-rpg-ui#1]
I enjoy this theme but I'd highly recommend renaming the `.private` folder. Its a common nginx configuration practice to disallow access to any hidden files or directories. When I first installed this, I had to turn to the dev tools to find out why the theme looked wrong. Turned out it was 403ing on the `.private` folder, so none of the images were loaded in. If you could change it to something without a leading period, it'd be more friendly for safe nginx setups.

**Comment by mouse0270** [comment]
Is it that it's hidden or that it starts with a dot? I don't have any nginx environments nor extremely familiar with them.

I'd prefer to keep the folder specifically labeled and at the top of my dev environment as it helps me make sure to never mix up uploading my licensed content to Github directly.

So if I just need to make the folder not hidden, that is something I can do, but if it's the period at the start, then I would like to know a better character to prefix it with. As I want it prefixed so its always at the start of my development environment .

**Comment by bojjenclon** [comment]
In Linux, a hidden file/folder is denoted by a period. So the dot is whats making it be considered hidden in this case. You could use an underscore instead perhaps?

**Comment by mouse0270** [comment]
Fixed: https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.3.4b

The folder will now be `_private`

**Comment by bojjenclon** [comment]
Thank you!
