### ISSUE TITLE
Enhancement - Setting to center the hotbar?

### ISSUE THREAD

**Issue by JacobSeibel** [mouse0270/fantasy-rpg-ui#10]
I'm migrating over from another theme, and one feature I'm missing is the centered hotbar. If possible, could you add an option to center the hotbar for this theme?

**Comment by mouse0270** [comment]
So I can add this feature, but it wont be getting added here. I plan on expanding TidyHUD in libThemer over the next few days. It will come with a feature to align the hotbar left, center or right.

So yes you can get this feature, but it will technically be apart of libThemer and not this theme specifically.

I will update this issue when I update that feature on libThemer tomorrow or thursday.

**Comment by JacobSeibel** [comment]
Awesome, thank you!

**Comment by mouse0270** [comment]
You can use the new feature in libThemer to center the hotbar under TidyHUD
