### ISSUE TITLE
UI not working

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#11]
Hi.

The UI is not working on 37b.
![image](https://user-images.githubusercontent.com/4999783/196297285-bee1bb22-9514-4185-9760-6e48d67b17b3.png)

I turn on everything.

Tips?

**Comment by mouse0270** [comment]
Make sure to click on the arrows on the left and make sure the things under them are enabled. This is a very modular theme.

You could also click on Manage Presets and then activate "Fantasy RPG UI"

**Comment by mouse0270** [comment]
Also are you on 0.3.7b or 0.3.7.1b?

**Comment by brunocalado** [comment]
> Also are you on 0.3.7b or 0.3.7.1b?

![image](https://user-images.githubusercontent.com/4999783/196298331-74b0437a-4247-4dc2-b9dd-0e99d04ac009.png)

**Comment by mouse0270** [comment]
Did you double-check the items under the arrow? Or go to manage presets and activate the theme again?

**Comment by brunocalado** [comment]
> Did you double-check the items under the arrow? Or go to manage presets and activate the theme again?
preset fixed. tks
