### ISSUE TITLE
Resize Window control is covered by header buttons when there are many header buttons

### ISSUE THREAD

**Issue by JacobSeibel** [mouse0270/fantasy-rpg-ui#13]
![image](https://user-images.githubusercontent.com/5156907/196769601-145fd680-229d-4549-b527-1a11badc536c.png)

I have a number of modules that add buttons to the header. I am unable to resize this window because the control is beneath the "ring" image.

**Comment by mouse0270** [comment]
I can see how that may be an issue... I should be able to make it so you can click through that part.

**Comment by mouse0270** [comment]
Pretty sure this should be resolved in 0.3.9, if not let me know. https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.3.9
