### ISSUE TITLE
Color Picker button in Compendium Folders module is too large

### ISSUE THREAD

**Issue by JacobSeibel** [mouse0270/fantasy-rpg-ui#14]
![image](https://user-images.githubusercontent.com/5156907/196796732-3554725a-a93b-457d-bd87-889568e42867.png)

The button covers part of the window.

**Comment by mouse0270** [comment]
I clearly screwed something up, only buttons in the button container should be styled. I will look at it later tonight. I have a late work day today

**Comment by JacobSeibel** [comment]
No rush! Thanks!

**Comment by mouse0270** [comment]
Sorry for the delay, I ended up working a 15-hour shift yesterday and just didn't get around to this until now.

Pretty sure this should be resolved in 0.3.9, if not let me know. https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.3.9

**Comment by JacobSeibel** [comment]
No worries about the delay! I get that this isn't your job! Make sure you take time to rest, yourself. I'm sure everyone appreciates the quick fixes, but take care of yourself! (Unless this is how you unwind!)
