### ISSUE TITLE
Incompatibility with Tidy Sidebar from libThemer

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#15]
Hi 

There is a weird line if you turn tidy ui on

https://user-images.githubusercontent.com/4999783/197429102-7c0437b8-69e7-4781-9b63-1246bdb66791.mp4

**Comment by mouse0270** [comment]
Not all theme options are compatible with each other, I will take a look and see what I can do to improve this, but I cant make any promises. If you are looking for a more compact setting sidebar menu in Fantasy RPG UI I can look at adding that as an option too.

I can look into improving this but I can't make any promises as Tidy Sidebar doesn't know that Fantasy RPG UI exists and vice versa. In short, I can see if I can make this less impactful, but I can't make any promises.

**Comment by mouse0270** [comment]
For example, if you disable Fantasy RPG UI Settings Sidebar, you will see the changes Tidy Sidebar makes and why those may not be as compatible with this specific theme.

**Comment by brunocalado** [comment]
Thank you. I thought it was part of the theme. 

It's ok.

**Comment by mouse0270** [comment]
LibThemer is a Library I wrote to manage CSS variables for developers to use to allow users to customize their experiance. Tidy HUD, Tidy Sidebar and even Colorize Foundry are all just examples of how to use libThemer.

Fantasy RPG UI is my attempt to show hot wo use libThemer as a library. lol

But like I said, if I can I will see if I can improve the look of the two themes when used at the same time.
