### ISSUE TITLE
Advancement windows.

### ISSUE THREAD

**Issue by Padhiver** [mouse0270/fantasy-rpg-ui#16]
Hi!
First of all, thank you for this fabulous UI, it's really great! 

I noticed that when you edit a progression in the class window, the style of the UI was a bit broken. I think it's because this little window isn't built like the rest of the system, but you'll probably know better than me!

Thanks again anyway, it's a fabulous job. :)
![image](https://user-images.githubusercontent.com/80126915/197774870-d6c3bdf9-6bc6-4b1d-aab5-696014d1f05d.png)

**Comment by mouse0270** [comment]
Can you tell me how to get to this window? I use D&D Beyond Importer, so I actually don't know how to get to this menu.

But you're most likely correct that the dialogue is doing something different and should be an easy fix.

**Comment by Padhiver** [comment]
Hey,
You need to open the details of a class, go to the Advancement tab, then edit by clicking on the small square on the right.
Note that not all advancement types have the concern, Features for example has the concern.

https://user-images.githubusercontent.com/80126915/197776985-b21b2bfd-eb1f-4cce-b831-dfb6354690d2.mp4

**Comment by mouse0270** [comment]
Should be resolved in v0.3.10. If you find any other issues please let me know.

https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.3.10

**Comment by Padhiver** [comment]
It's fixed, thank you ! o/
