### ISSUE TITLE
Inspiration button disappears

### ISSUE THREAD

**Issue by Padhiver** [mouse0270/fantasy-rpg-ui#17]
Hello', it's me again !
Sorry to be the bird of ill omen!

I found a new little problem, when you press the inspiration button, it disappears and does not come back.
If you deactivate your UI, then inspiration is checked, so there you go.

https://user-images.githubusercontent.com/80126915/197869490-43ec7d40-85c1-402b-b588-3c405e4acdcf.mp4

Sorry again and if you need any clarification, don't hesitate!

**Comment by Padhiver** [comment]
Oh, another one, again in advancement tab, I think it's probably the same problem?

https://user-images.githubusercontent.com/80126915/197870858-5b0d96d9-9851-4ed6-a815-c6c3078645af.mp4

**Comment by mouse0270** [comment]
Can you send me a screenshot of your console after checking one of those inputs. I suspect its failing to grab an image.

**Comment by Padhiver** [comment]
> Can you send me a screenshot of your console after checking one of those inputs. I suspect its failing to grab an image.

I don't have any error unfortunately. :X

I dont know if that can help, but in generic-windows-input.css, if i remove line 13, 14 and 15, this solves the problem, even if it probably creates others? :'D

  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;

**Comment by mouse0270** [comment]
Well, that works cause you're disabling the custom checkboxes. lol I should have some time to look at this tomorrow to resolve the issue.

**Comment by mouse0270** [comment]
This should be resolved in v0.4.0 https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.4.0
