### ISSUE TITLE
Request - Alternate style for GM Only chat messages

### ISSUE THREAD

**Issue by JacobSeibel** [mouse0270/fantasy-rpg-ui#18]
Although I vastly prefer the aesthetic of the chat theme, one thing I find myself missing is the ability to visually distinguish public rolls/messages from GM Only ones.

Could we get an option to select an alternate style for GM Only or Private messages?

**Comment by mouse0270** [comment]
That is why I made it so you can disable the parchment for chat cards.

I do want to add a more themed approach for handling these chat cards, I just haven't thought of a way to do so...  I am open to any suggestions you might have to make rolls looks unique. I was thinking of maybe adding a circle in the top left of the color, so you could at least tell the difference, but I think this might be too minimal to notice.

**Comment by JacobSeibel** [comment]
Would it be possible to choose an alternate style from the existing list for private/GM chat cards? Like how you have "Foreground Image" for other parts, like the Dialog Theme settings. Could you have "Public Chat Cards" "Private Chat Cards" "GM Chat Cards" and let the user choose from the existing styles (rock, parchment, wood, etc)?

**Comment by mouse0270** [comment]
Well making it GM-specific would be complicated, but letting you choose a different background for different options be easy. I think I could even boot up photoshop and make duplicates of the parchment texture but in different colors to allow you to pick different colors that way.

**Comment by mouse0270** [comment]
Just so you know, I didn't forget about you. I am hoping to push this update out today. It adds a ton of color variations for the parchment and allows you to set chat messages with a specific background. Currently, It supports the default chat message, whisper, and blind. As those are the only ones I know of if I am missing any let me know!!!

![image](https://user-images.githubusercontent.com/564874/199551956-612d2adf-7b17-49cc-9a8a-23157cde95bf.png)

**Comment by mouse0270** [comment]
This should be resolved in v0.4.0 https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.4.0

**Comment by JacobSeibel** [comment]
This is awesome! Thanks again!!

**Comment by mouse0270** [comment]
Let me know if I need to add any more options. Those were the only 3 I could find. I am actually pretty noob at using foundry. lol
