### ISSUE TITLE
Always Update 

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#20]
Hi!

Everytime you press update all you got this:

![image](https://user-images.githubusercontent.com/4999783/198745707-8fd497ec-2739-402b-9ad9-3cfb4b29ce7d.png)

There is some bug with manifest or fvtt site

Tks

**Comment by mouse0270** [comment]
It appears that the packaged manifest says its version 0.3.10 instead of 0.3.10.1, so the package manager things it needs update. EZ fix and will make sure the version is correct in the next update.

**Comment by mouse0270** [comment]
This should be resolved in v0.4.0 https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.4.0
