### ISSUE TITLE
v11 Compatability

### ISSUE THREAD

**Issue by Heljspe** [mouse0270/fantasy-rpg-ui#29]
I love this mod, please update so we can use it on version 11! <3 

Currently personally on V11.302 for DnD5e - Fifth Edition System 2.2.2

Forge is saying it's not compatible and won't let me turn the mod on. 

![image](https://github.com/mouse0270/fantasy-rpg-ui/assets/68180128/4e253675-b91a-467a-9c11-f6ae99ffabdb)

**Comment by RandomLegend** [comment]
i'd love to have this on v11 aswell. 

I waited to change to v11 for quite a few months now and the final thing i am missing is this UI.... the default one looks so boring and bland and as far as i can see there are no real competitors... DnD 5e UI looks awful compared to this tbh.

**Comment by davidhawbecker** [comment]
I want to echo these comments. Such a good looking mod. Hope it makes it to v11.

**Comment by mouse0270** [comment]
This should be done, for both v11. Well it will let you install it. I plan to update it in the future as I just got back to foundry development.

**Comment by davidhawbecker** [comment]
I can load the module in v11 now, but I don't see any changes to the UI.

**Comment by mouse0270** [comment]
> I can load the module in v11 now, but I don't see any changes to the UI.

Have you made sure it's enabled via libThemer?

**Comment by davidhawbecker** [comment]
Ha. Brilliant. Forgot about that one. That did it. Thank you.
