### ISSUE TITLE
Custom Logo

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#3]
Hi. Great module.

Can you add an option to replace the hammer icon by something else?

tks

**Comment by mouse0270** [comment]
I probably could, It would have to be a square icon. I really don't have a way for it to determine the width, so it just sets the height and width to 50px;

**Comment by brunocalado** [comment]
> I probably could, It would have to be a square icon. I really don't have a way for it to determine the width, so it just sets the height and width to 50px;

The easy way is to force the user to use a default image size.

To change the logo using Minimal UI I have to use a image 150x50.

**Comment by mouse0270** [comment]
I mean I don't really care what the image size is, as long as it's square. I honestly don't think Id do much validation, you choose an image if it looks weird, then changes the image. lol

Unless the FilePicker API has a way to have you choose images that are a specific size, that would be different, but I don't think it does, so I assume if Minimum UI is doing this, it's adding its own logic.

Either way, I am down for adding this feature.

**Comment by mouse0270** [comment]
This requires an update to libThemer to accomplish. I haven't forgotten about it, just takes an additional step.

**Comment by mouse0270** [comment]
Didn't forget about you, just took a bit to get around to this. As I had to fix some other stuff with libThemers image property.

Should be resolved in v0.3.10. If you find any other issues please let me know.

https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.3.10
