### ISSUE TITLE
Quest Log Compatibility

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#4]
Hi.

Can you make it work well with QL module? https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log

https://user-images.githubusercontent.com/4999783/195914932-440f810c-750b-4950-a3b2-34bf134947a4.mp4

**Comment by mouse0270** [comment]
Sure, I'll do it later tonight or this weekend depending on complexity

**Comment by mouse0270** [comment]
Should be resolved in version 0.3.7.1
