### ISSUE TITLE
Better Rolls Compatibility

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#5]
Hi.

Can you make it align with Better Rolls 2? https://github.com/javierriveracastro/betteroll-swade

![image](https://user-images.githubusercontent.com/4999783/195933311-503a4df8-35a0-4262-8d77-08bdd963df22.png)

Tks

**Comment by mouse0270** [comment]
Sure, I'll do it later tonight or this weekend depending on complexity

**Comment by mouse0270** [comment]
Are you able to take a screen shot of your inspector and show me the html and css for that container? I am not sure whats going on. I can't really tell whats going on cause it appears to be working for  me.

The worse case could always talk on discord if you are comfortable sharing your screen with me.

**Comment by brunocalado** [comment]
> Are you able to take a screen shot of your inspector and show me the html and css for that container? I am not sure whats going on. I can't really tell whats going on cause it appears to be working for me.
> 
> The worse case could always talk on discord if you are comfortable sharing your screen with me.

I PM you

**Comment by mouse0270** [comment]
Should be resolved in version 0.3.7.1
