### ISSUE TITLE
Small Time Compatibility

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#6]
Hi.

This settings mess happens only with small time. Can you fix this or I should ask the small time dev?

https://user-images.githubusercontent.com/4999783/195938025-f17527a2-cbd8-4ac7-ae90-760625becba8.mp4

tks

**Comment by mouse0270** [comment]
Interesting I assume smalltime must be doing something odd in the settings window. I'll take a look and resolve it.

**Comment by mouse0270** [comment]
Should be resolved in version 0.3.7.1
