### ISSUE TITLE
Turn Off Style Option for Actor Sheet 

### ISSUE THREAD

**Issue by brunocalado** [mouse0270/fantasy-rpg-ui#7]
Hi!

Savage pafthinder makes heavy style changes. Is it possible to add an option to turn off style modification for actors?

UI Off
![image](https://user-images.githubusercontent.com/4999783/195938569-14161896-5cb0-459e-aa58-1ae7472a369f.png)

I loose all buttons when the UI is on... :(

UI On
![image](https://user-images.githubusercontent.com/4999783/195938899-bdf5ed0e-9c5b-49b4-b42a-c1048f46e1b8.png)

**Comment by mouse0270** [comment]
Do you want me to disable the theme for actor sheets or fix the header buttons being hidden? Cause honestly the ui basically works minus the buttons being hidden cause of an overflow property

**Comment by brunocalado** [comment]
> Do you want me to disable the theme for actor sheets or fix the header buttons being hidden? Cause honestly the ui basically works minus the buttons being hidden cause of an overflow property

What is easier. I fear all changes from the swpf + ui give some trouble. Maybe disable for the actor sheet.

**Comment by JacobSeibel** [comment]
I'll second that I'd like to be able to disable the theme altogether for actor sheets via a setting. I use Tidy5e Character Sheets, and I'd love to continue using the theme everywhere else until support is added for Tidy5e.

**Comment by mouse0270** [comment]
Alright, I can pull actor sheets out so they can be abled separately from everything else. I get that update out today.

**Comment by mouse0270** [comment]
Can you link me the module or system that is creating this Actor Sheet. I can't seem to find it.

**Comment by brunocalado** [comment]
> Can you link me the module or system that is creating this Actor Sheet. I can't seem to find it.

It's a premium (paid) module...

What do you need?

**Comment by mouse0270** [comment]
Would you be able to test this release and let me know if it resolves the issues for all of your open tickets?

https://github.com/mouse0270/fantasy-rpg-ui/releases/download/0.3.7b/module.json

**Comment by brunocalado** [comment]
small time ok
https://user-images.githubusercontent.com/4999783/196013520-809c7901-7bb1-4b6f-8256-c7fc9468b27d.mp4

better rolls 2 nok
![image](https://user-images.githubusercontent.com/4999783/196013548-4e5428c9-2331-4566-82e4-5970a178ca36.png)

quest log ok
![image](https://user-images.githubusercontent.com/4999783/196013569-02e7990a-251f-430b-99c5-a8cc0ebaa703.png)

actor sheet nok
![image](https://user-images.githubusercontent.com/4999783/196013609-227a9351-77ff-4f89-bca8-d87cf56bb066.png)

custom logo couldn't find option

**Comment by mouse0270** [comment]
you might have to enable the module in the theme. I might have forgot to add them to the update logic.

**Comment by brunocalado** [comment]
> you might have to enable the module in the theme. I might have forgot to add them to the update logic.

![image](https://user-images.githubusercontent.com/4999783/196013665-c53e3088-cdae-4faa-b10c-fd7b5f857843.png)
What should I do?

**Comment by mouse0270** [comment]
In the sidebar, click on `Configure Theme` then Go to `Fantasy RPG UI` and make sure those modules are enabled.
![image](https://user-images.githubusercontent.com/564874/196013710-8e2ee6cf-e956-4d55-9450-66a12aea29ed.png)

I just noticed I forgot localization for Better Rolls

**Comment by brunocalado** [comment]
quest log ok
![image](https://user-images.githubusercontent.com/4999783/196013740-0ac9af22-994f-4887-9cbe-fc92f03128d7.png)

**Comment by mouse0270** [comment]
Is Better Rolls broken still?

**Comment by brunocalado** [comment]
actor sheet buttons are invisible, but show on mouse over
https://user-images.githubusercontent.com/4999783/196013798-55301fee-38af-4ae6-89fe-96550af751a4.mp4


better rolls 2
![image](https://user-images.githubusercontent.com/4999783/196013821-e0b12656-049a-4af8-b187-61fd50ece77b.png)

**Comment by mouse0270** [comment]
The actor sheet is a bug with libThemer. If you click on the arrow next to `Enable Theme for Actor Windows` you should be able to uncheck the `Hide Header Buttons`

This is something I need to fix in libThemer that if you disable a top level checkbox, it should disable all the ones below it.

Do you have any errors? It seems to be working for me, so I am not sure whats going on for you.

**Comment by brunocalado** [comment]
> 
Nice!
![image](https://user-images.githubusercontent.com/4999783/196013984-f41e3a8e-4b86-4e23-8ac5-ecb934a98e24.png)

Everything ok.

**Comment by brunocalado** [comment]
I don't know if this means something
![image](https://user-images.githubusercontent.com/4999783/196014017-27e8960f-8682-411e-9fe4-dbabd26c8cf7.png)

**Comment by mouse0270** [comment]
Alright, I am going to switch over to the better rolls issue to continue this. Because it appears this specific issue will be resolved

**Comment by mouse0270** [comment]
Should be resolved in version 0.3.7.1
