### ISSUE TITLE
Button style on dialog box covers text on Midi-QOL's Reaction prompt

### ISSUE THREAD

**Issue by JacobSeibel** [mouse0270/fantasy-rpg-ui#8]
![image](https://user-images.githubusercontent.com/5156907/195967844-01b9827e-eac2-4686-a889-fd966cf30248.png)

When a player is prompted for a Reaction by Midi-QOL in DnD5e, the buttons in the dialog box cover the text.

**Comment by mouse0270** [comment]
I guess I have to handle if a dialog button has an image... interesting. I will fix this this weekend.

**Comment by mouse0270** [comment]
Would you be able to test this release and let me know if it resolves the issues for this ticket?

https://github.com/mouse0270/fantasy-rpg-ui/releases/download/0.3.7b/module.json

**Comment by mouse0270** [comment]
Should be resolved in version 0.3.7.1

If not, reopen this issue.

**Comment by JacobSeibel** [comment]
Hey there! Sorry I took so long to get back with you. Unfortunately, the issue does seem to persist for me:

![image](https://user-images.githubusercontent.com/5156907/196198594-b7ab0e5a-817a-4a09-b0f1-df4a28bacfb5.png)

**Comment by mouse0270** [comment]
Thats fine, I kinda took a guess, cause I don't have MIDI setup, so I am not getting these dialogs. Looks like I will have to setup MIDI - QOL

**Comment by JacobSeibel** [comment]
The setting to enable these prompts is here:

![image](https://user-images.githubusercontent.com/5156907/196257744-58ca28bf-4626-466a-aa9b-5e9cf1705883.png)

![image](https://user-images.githubusercontent.com/5156907/196257889-48b1a228-1fc8-491d-826f-c280f92cd097.png)

**Comment by mouse0270** [comment]
Should be resolved in version 0.3.8
